### ISSUE TITLE
Assuming yaml isn't safe for all python3

### ISSUE THREAD

**Issue by tmbgreaves** [alan-turing-institute/binderhub-deploy#26]
```
--> Generating initial configuration file
Traceback (most recent call last):
  File "/home/tmb1/binderhub-deploy/create_config.py", line 16, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
[tmb1@ese-bbotworker04 binderhub-deploy]$ python3
Python 3.6.8 (default, Apr 25 2019, 21:02:35) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'yaml'
>>> 
```

**Comment by tmbgreaves** [comment]
Fixed in PR #22 - https://github.com/alan-turing-institute/binderhub-deploy/pull/22/commits/54faf00666f66d347a44d087aa7aa7f84fa00fba
